### ISSUE TITLE
node-expat build error

### ISSUE THREAD

**Issue by khanghuynh92** [dkiyatkin/node-office#15]
Anyone please help me check this error when I try to install office lib. Thank you so much

OS Ubuntu 14.04
Node: v4.4.0
npm: v.2.14.20
python: v2.6.9

```
root@gorillab:/home/apps/lsb.gorillab.co# make: Leaving directory `/home/apps/lsb.gorillab.co/node_modules/office/node_modules/xml2json/node_modules/node-expat/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 3.13.0-83-generic
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/apps/lsb.gorillab.co/node_modules/office/node_modules/xml2json/node_modules/node-expat
> gyp ERR! node -v v4.4.0
> gyp ERR! node-gyp -v v3.3.0
> gyp ERR! not ok
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> npm ERR! Linux 3.13.0-83-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "office"
> npm ERR! node v4.4.0
> npm ERR! npm  v2.14.20
> npm ERR! code ELIFECYCLE
>
> npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-expat@2.0.0 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the node-expat package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-expat
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls node-expat
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/apps/lsb.gorillab.co/npm-debug.log
```

**Comment by DiogoAngelim** [comment]
Try installing node-expat manually: 

$ npm install node-expat@2.3.13
$ npm install

I hope this helps.

**Comment by chevalierc** [comment]
I had the same error. manually installing did not work unforunatly

**Comment by Osturrock** [comment]
Same problem (node = 6.9.1). The manual installation of node-expat works, but doesn't solve the build issues during office installation.

**Comment by Teddy95** [comment]
I had the same error like @Osturrock
