### ISSUE TITLE
Installation error on my windows 8 system. I am using node js v0.8.18, express v3.2.0.

### ISSUE THREAD

**Issue by ranjith41989** [dkiyatkin/node-office#6]
D:\office work\projects>npm install office
npm WARN package.json application-name@0.0.1 No README.md file found!
npm WARN package.json cradle@0.6.4 No README.md file found!
npm http GET https://registry.npmjs.org/office
npm http 200 https://registry.npmjs.org/office
npm http GET https://registry.npmjs.org/office/-/office-0.0.6.tgz
npm http 200 https://registry.npmjs.org/office/-/office-0.0.6.tgz
npm http GET https://registry.npmjs.org/xml2json
npm http GET https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/xml2json
npm http GET https://registry.npmjs.org/temp/-/temp-0.5.1.tgz
npm http 200 https://registry.npmjs.org/temp/-/temp-0.5.1.tgz
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/node-expat/2.0.0
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.1.4.tgz
npm http 304 https://registry.npmjs.org/node-expat/2.0.0
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.1.4.tgz
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/graceful-fs

> node-expat@2.0.0 install D:\office work\projects\nod
> e_modules\office\node_modules\xml2json\node_modules\node-expat
> node-gyp rebuild

D:\office work\projects\node_modules\office\node_modul
es\xml2json\node_modules\node-expat>node "C:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [D:\office work\projects\nod
e_modules\office\node_modules\xml2json\node_modules\node-expat\build\binding.sl
n]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.e
xe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\office work\projects\node_modules\offi
ce\node_modules\xml2json\node_modules\node-expat
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok
npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the node-expat@2.0.0 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "office"
npm ERR! cwd D:\office work\projects
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\office work\projects\npm-debug.log
npm ERR! not ok code 0

**Comment by mytharcher** [comment]
Almost same problem on my Mac:

``` shell
npm http GET https://registry.npmjs.org/office
npm http 304 https://registry.npmjs.org/office
npm http GET https://registry.npmjs.org/xml2json
npm http GET https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/xml2json
npm http GET https://registry.npmjs.org/xml2json/-/xml2json-0.3.2.tgz
npm http 200 https://registry.npmjs.org/xml2json/-/xml2json-0.3.2.tgz
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/node-expat/2.0.0
npm http 304 https://registry.npmjs.org/node-expat/2.0.0
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/graceful-fs

> node-expat@2.0.0 install /Users/mytharcher/work/findyha/crawl/node_modules/office/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
npm http 304 https://registry.npmjs.org/graceful-fs
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mytharcher/work/findyha/crawl/node_modules/office/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok 
unbuild node-expat@2.0.0
unbuild xml2json@0.3.2
unbuild office@0.0.6
npm ERR! weird error 1
npm ERR! not ok code 0
```

My node version is v0.10.13.

**Comment by James1x0** [comment]
@mytharcher @ranjith41989
Same error on Linux centOS, there's a bug in the source. #10 
_Author seems unresponsive. I've installed https://npmjs.org/package/textract instead._
