### ISSUE TITLE
A "spawn ENOENT" error

### ISSUE THREAD

**Issue by exolution** [dkiyatkin/node-office#9]
my code is

``` javascript
var office=require('office'),fs=require('fs');
console.log(fs.statSync('./test.doc'));// no error
office.parse('test.doc',function(err,data){}); 
```

follows is error text:

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

the file "test.doc" is -rwxr-xr-x


thanks~
```

**Comment by bbaaxx** [comment]
I'm having the exact same issue running node v0.10.24.

**Comment by pavel-mxsf** [comment]
Me too, on Windows 7 x64

**Comment by palin27** [comment]
Me too on OSX 10.7.5!

**Comment by m4a1fox** [comment]
Me too. Looks like t doesn't fixed?!

**Comment by palin27** [comment]
I guess unoconv installation is a mandatory requirement in fact fails when child_process call unoconv.

**Comment by chenop** [comment]
It seems that unoconv is not suitable for Windows - Is that true?

**Comment by m4a1fox** [comment]
Don't know that yet. But I'll try to install this module for 2 day. Not luck yet. But in my other notebook Mac - All starts work nice. P.S. Thanks man for this module.

**Comment by chenop** [comment]
Any update on this one? 
At Windows 7 64bit, got:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process._handle.onexit (child_process.js:779:34)

**Comment by dkiyatkin** [comment]
I dev this module for linux only... This module does not support Windows. it will happen in the future... maybe.

**Comment by m4a1fox** [comment]
Thanks man. You save my time.

**Comment by thehack** [comment]
I'm getting the same issue in OS X.
